//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingDBase5ticg3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biografia
    {
        public int Id { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public string StrValor { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual personas personas { get; set; }
    }
}
