//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingDBase5ticg3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestDbMensajeriaEntities : DbContext
    {
        public TestDbMensajeriaEntities()
            : base("name=TestDbMensajeriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<direcciones> direcciones { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<personas> personas { get; set; }
        public virtual DbSet<profesiones> profesiones { get; set; }
        public virtual DbSet<profesionesPersonas> profesionesPersonas { get; set; }
        public virtual DbSet<telefonos> telefonos { get; set; }
    }
}
